resources:
  repositories:
  - repository: mobile_tests # The name used to reference this repository in the checkout step
    type: github
    endpoint: LapasPerformance
    name: LapasPerformance/mobile_tests

trigger:
- master

pool:
  name:  NIMBUSCLIENT
steps:
- checkout: mobile_tests
  path: PutMyCodeHere
