resources:
  repositories:
  - repository: mobile_tests # The name used to reference this repository in the checkout step
    type: github
    endpoint: LapasPerformance
    name: LapasPerformance/mobile_tests

trigger:
- master

pool:
  name:  Default
steps:
- checkout: mobile_tests
  path: 

- task: RunFromFileSystemTask@1
  inputs:
    testPathInput: '$(Agent.BuildDirectory)\PutMyCodeHere\Sample_test_Mobile_1'
